### ISSUE TITLE
synthetics-minion does not set QoS Guaranteed when resources are applied correctly

### ISSUE THREAD

**Issue by mikeroth** [newrelic/helm-charts#1078]
**Bug description**

When resources are applied so the requests match the limits the QoS still shows Burstable when it should be showing Guaranteed.

```
  resources:
    requests:
      cpu: "750m"
      memory: "1600Mi"
    limits:
      cpu: "750m"
      memory: "1600Mi"
```

**Version of Helm and Kubernetes**

Deployed with ArgoCD v2.5.0+b895da4
Helm: v3.10.0
Kubernets: 1.24

**Which chart?**

newrelic https://helm-charts.newrelic.com
newrelic/synthetics-minion --version 1.0.59

**What happened?**

When settings get applied a new stateful set is created with a new pod. Doing a describe on the pod I can see the resources set to below, BUT the QoS is still set to burstable when it should be guaranteed.
 
```
  Limits:
    cpu:     750m
    memory:  1600Mi
  Requests:
    cpu:     750m
    memory:  1600Mi
```

**What you expected to happen?**

QoS should be Guaranteed on the pod and not Burstable.

**How to reproduce it?**

Deploy the manifest with the values below.

```
          synthetics:
            privateLocationKeySecretName: nr-syn-secret
          resources:
            requests:
              cpu: "750m"
              memory: "1600Mi"
            limits:
              cpu: "750m"
              memory: "1600Mi"
```

**Anything else we need to know?**

Surprise us!
