### ISSUE TITLE
[nri-bundle] Global tolerations not propagating correctly

### ISSUE THREAD

**Issue by hero-david** [newrelic/helm-charts#1091]
**Bug description**

Global toleration values are not propagated properly to downstream charts (newrelic-infrastructure).
This causes daemonset pods to stay pending indefinitely when a taint is applied, despite us trying to allow the daemonset to tolerate it.

**Version of Helm and Kubernetes**

```$ kubectl version --short
Client Version: v1.25.5
Kustomize Version: v4.5.7
Server Version: v1.25.5
```
```
$ helm version
version.BuildInfo{Version:"v3.11.3", GitCommit:"323249351482b3bbfc9f5004f65d400aa70f9ae7", GitTreeState:"clean", GoVersion:"go1.20.3"}
```

**Which chart?**

nri-bundle and nri-infrastructure 

**What happened?**

When I use the following settings to create tolerations:
```yaml
global:
  tolerations:
    - key: role
      operator: Exists
      effect: NoSchedule
```

I receive the following template for my nri-daemonset:
```yaml
kind: DaemonSet
metadata:
  ...
  name: nri-test-nrk8s-kubelet

      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
```

**What you expected to happen?**

I expect the "key" attribute to be propagated to the daemonset.

**How to reproduce it?**

Create this file:

```yaml
# test.yaml
global:
  # licenseKey: <set in helm_newrelic.tf>
  # cluster: <set in helm_newrelic.tf>
  lowDataMode: true
  tolerations:
    - key: role
      operator: Exists
      effect: NoSchedule
```

1. Execute the following template step: `helm template nri-test newrelic/nri-bundle -f test.yaml --set global.cluster="test" --set global.licenseKey="test" > template.yaml`
2.  Find the `nri-test-nrk8s-kubelet` Daemonset in the `template.yaml` output
3. Observe the missing toleration attributes

**Anything else we need to know?**

I will be avoiding the use of `global.*` settings in this repository in the future, and instead just repeating the toleration across sub-chart config. We were also caught out by the fact that the [logging chart does not respect the global attributes](https://github.com/newrelic/helm-charts/blob/6de93297e035ba04971196d20dabe7d28dff54bd/library/common-library/README.md?plain=1#L24) currently.
