### ISSUE TITLE
[nri-bundle] cannot disable KSM

### ISSUE THREAD

**Issue by elebertus** [newrelic/helm-charts#1093]
**Bug description**

setting the values:
```
ksm:
  enabled: false
kube-state-metrics:
  enabled: false
```
does nothing.

**Version of Helm and Kubernetes**

helm 3.11.x
kube 1.23

**Which chart?**

nri-bundle 3.12.0

**What happened?**

see description

**What you expected to happen?**

Disabling one or both of these values should disable ksm

**How to reproduce it?**

Observe the ksm.enabled and kube-state-metrics.enabled values having no effect.

**Anything else we need to know?**

There is a caveat in the chart saying newrelic-infrastructure requires KSM, and the compatibility value that is constructed from ksm.enabled should indeed not include the chart, but it still does. I'm puzzled.

**Comment by svetlanabrennan** [comment]
Closing issue: ksm can be disabled with:

```yml
newrelic-infrastructure: 
   ksm: 
     enabled: false
```
