### ISSUE TITLE
[newrelic/nri-bundle] <enable Mongodb monitoring?>

### ISSUE THREAD

**Issue by nickpapadonis** [newrelic/helm-charts#1123]
I installed the nri-bundle chart, and everything seems to come up in my Kubernetes cluster.

I would like to monitor a MongoDB cluster as installed per Bitnami charts, which installs the side car Prometheus exporter.
https://github.com/bitnami/charts/tree/main/bitnami/mongodb

using values.yaml:
metrics:
  enabled: true
  extraFlags: "--collect-all --discovering-mode=true"

What is the next step?

I'm trying to follow the New Relic MongoDB instructions (containerized section) at:
https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new/

The only next steps are configuring the Prometheus agent as follows, however I have no idea where this configuration is supposed to go:
# (...)
new_relic_remote_write:
  extra_write_relabel_configs:
    - source_labels: [__name__]
      regex: 'mongodb_.*'
      target_label: mongodb_cluster_name
      replacement: 'cluster-name-example'

Thanks

**Comment by nickpapadonis** [comment]
Is this issue only visible internally to NR? I’m unable to access it. ThanksOn Jul 26, 2023, at 5:55 PM, workato-integration[bot] ***@***.***> wrote:﻿
https://issues.newrelic.com/browse/NR-146234

**Comment by nickpapadonis** [comment]
Found this:
https://github.com/newrelic/nri-mongodb/blob/master/mongodb-config.yml.k8s_sample

**Comment by nickpapadonis** [comment]
I created the attached values.yaml to monitor the bitnami/mongodb chart installation which usese metrics.enabled=true (enables prometheus side car).  I expected to see mongo added to the ConfigMap for the NR infrastructure agent, however only see the following.  Am I following the procedure correctly?

```
# Source: nri-bundle/charts/newrelic-infrastructure/templates/controlplane/agent-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: newrelic
  labels:
    app.kubernetes.io/instance: nr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: newrelic-infrastructure
    app.kubernetes.io/version: 3.15.1
    helm.sh/chart: newrelic-infrastructure-3.20.1
  name: nr-nrk8s-agent-controlplane
data:
  newrelic-infra.yml: |-
    # This is the configuration file for the infrastructure agent. See:
    # https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings/
    custom_attributes:
      clusterName: cluster-0
    http_server_enabled: true
    http_server_port: 8001
    is_forward_only: true
```
[nri-bundle-values.yaml.scrub.txt](https://github.com/newrelic/helm-charts/files/12178516/nri-bundle-values.yaml.scrub.txt)
