### ISSUE TITLE
[nri-bundle:5.0.26] Logs not parsing as CRI but parsing as Docker

### ISSUE THREAD

**Issue by JPrice904** [newrelic/helm-charts#1148]
**Logs not parsing as CRI**

Upgraded the NRI Bundle from 4.9.3 -> 5.0.26 and observed attributes that were previously available no longer available to filter on and log messages that were once being parsed with the CRI configuration were now appearing to be parsed with the Docker configuration. 

**Version of Helm and Kubernetes**

Helm chart installed via ArgoCD running on OpenShift 4.11

**Which chart?**

nri-bundle 5.0.26 which uses newrelic-logging 1.18.1

**What happened?**

After the upgrade the message field for springboot applications was now unfiltered and one long json message.

**What you expected to happen?**

I was expecting the upgrade to make no large changes to the logging format or for docker to truly be the fallback option and for CRI to remain the desired parsing format.

**Anything else we need to know?**

I am maintaining the nri-bundle version and deploying it with ArgoCD and Kustomization.  I was able to patch the environment variable utilizing patches with kustomization so that cri was the only value in the LOG_PARSER env variable.  Once that was done logs appeared to be normal again with additional attributes and json parsing fixed.

**Kustomization file**
```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml
  - ./scc.yaml

helmCharts:
  - name: nri-bundle
    repo: https://helm-charts.newrelic.com
    version: "5.0.26"
    releaseName: newrelic-bundle
    namespace: newrelic
    valuesFile: values.yaml

patches:
  - target:
      kind: DaemonSet
      name: newrelic-bundle-newrelic-logging
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/5
        value:
          name: LOG_PARSER
          value: cri
```
