### ISSUE TITLE
nri-bundle Alias Dependencies

### ISSUE THREAD

**Issue by huggabear91** [newrelic/helm-charts#117]
We should alias the chart dependencies in the nri-bundle umbrella chart. Currently our values file must like like this

```
infrastructure:
  enabled: true

newrelic-infrastructure:
  enableLinux: true
  enableWindows: true

```
When ideally we could do this

```
infrastructure:
  enabled: true
  enableLinux: true
  enableWindows: true
```

This should only require us to update the requirements.yaml to look like this

```
dependencies:
  - name: newrelic-infrastructure
    repository: file://../newrelic-infrastructure
    condition: infrastructure.enabled
    version: 1.3.1
    alias: infrastructure
```
