### ISSUE TITLE
[nri-bundle] <nri-mongodb3 integration is not working>

### ISSUE THREAD

**Issue by nandoin** [newrelic/helm-charts#1310]
**Bug description**

Integration in nri-bundle is not working for nri-mongodb3

**Version of Helm and Kubernetes**

Kubernetes v1.28
Helm v3.14.0
Atlas M20

**Which chart?**

nri-bundle:5.0.46

**What happened?**

I'm trying to configure newrelic-infrastructure with integrations (nri--mongodb3), but when i deploy helm, i get a error message in newrelic-bundle-nrk8s-kubelet-xxxx pod container agent.
![mongodb-error2](https://github.com/newrelic/helm-charts/assets/50249756/da0b104f-262b-44f0-a5c6-1b9374467e87)

**What you expected to happen?**

I want to monitor MongoDB Atlas with newrelic-infrastruture agent on kubernetes. 

**How to reproduce it?**
values.yaml
````
newrelic-infrastructure:
  enabled: true
  integrations:
    mongodb3-config.yml:
      integrations:
        - name: nri-mongodb3
          config:
            mongodb_cluster_name: ${cluster-name}
            mongodb_uri: mongodb+srv://${user}:${password}@${server}/?retryWrites=true&w=majority
            mongodb_direct_connect: false
            collection_filters:
            index_filters:
            database_stats: true
            collection_stats: true
            index_stats: true
            replicaset_stats: true
            top_stats: true
            diagnostic_stats: true
            exporter_port: 9126
            scrape_timeout: 30s
````
![mongodb-error](https://github.com/newrelic/helm-charts/assets/50249756/3a9713ec-3518-4dad-96f0-5f913dc76a3a)

**Anything else we need to know?**
