### ISSUE TITLE
[nri-bundle:5.0.69] Update Docs: "fluentBit.k8sLoggingExclude" needs to be 'true' and not 'On'

### ISSUE THREAD

**Issue by brenwhyte** [newrelic/helm-charts#1312]
**Docs need updating**

Using nri-bundle 5.0.69 and I've tested this in a kind cluster

**Version of Helm and Kubernetes**
Helm = v3.14.0
k8s (kind) = v1.25.3

**Which chart?**

nri-bundle 5.0.69

**What happened?**

Setting `fluentBit.k8sLoggingExclude` to 'On' fails to ignore logs set with the `fluentbit.io/exclude: true` annotation

**What did you expect to happen?**

I expected once I set `fluentBit.k8sLoggingExclude` to 'On' as per the [docs](https://github.com/newrelic/helm-charts/blob/44ecf193093519ad07611b9f249bfede44c3fd97/charts/newrelic-logging/README.md?plain=1#L142) I could use annotations to ignore pod logs

Also covered here
https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#kubernetes-annotations

**Anything else we need to know?** 

If I set `fluentBit.k8sLoggingExclude` to 'true' it works as expected.

```
newrelic-logging:
  enabled: true
  fluentBit:
    k8sLoggingExclude: true
```

```
spec:
  replicas: 1
  selector:
    matchLabels:
      *snip*
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: Helm
        *snip*
        helm.sh/chart: ingress-nginx-4.10.0
      annotations:
        fluentbit.io/exclude: 'true'
```
