### ISSUE TITLE
[newrelic-infrastructure] Inconsistent ConfigMap names

### ISSUE THREAD

**Issue by sadortun** [newrelic/helm-charts#143]
Hi,

In https://docs.newrelic.com/docs/integrations/kubernetes-integration/link-apps-services/monitor-services-running-kubernetes#configmap

We have this:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-integration-cfg
  namespace: default
data:
```

But in the chart you have a different name :
https://github.com/newrelic/helm-charts/blob/8efddfdd73e6972f5ec8ba660966a9a115c9a60f/charts/newrelic-infrastructure/templates/daemonset.yaml#L214

Either update the doc, or the chart, but there is no reason for having different names! 

Thanks!
