### ISSUE TITLE
[nri-bundle] We should document how to modify configs in chart dependencies

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/helm-charts#154]
When deploying nri-bundle chart it is possible to modify values for the dependencies charts:
 - Helm documentation: https://helm.sh/docs/chart_template_guide/subcharts_and_globals

This is possible already but I believe we should add at least a hint with some common configs to show how to do so
Es:
```yaml
#values.yaml of nri-bundle
infrastructure:
  enabled: true
# <removed the rest for brevity>
# configure the k8s integration dependency
newrelic-infrastructure:
#  enableLinux: true
# enableWindows: false
#  verboseLog: false
#  image:
#    repository: newrelic/infrastructure-k8s
#    tag: ""
#    windowsTag: 1.21.0-windows-1809-alpha
#    pullPolicy: IfNotPresent
# configure another dependency
nri-kube-events:
  key: value
```
