### ISSUE TITLE
nri-bundle YAML error in daemonset-windows.yaml on deployment

### ISSUE THREAD

**Issue by dbarentine** [newrelic/helm-charts#158]
**Bug description**

When deploying the nri-bundle helm template I get the following error:
Error: UPGRADE FAILED: YAML parse error on nri-bundle/charts/newrelic-infrastructure/templates/daemonset-windows.yaml: error converting YAML to JSON: yaml: line 54: did not find expected key

**Version of Helm and Kubernetes**

Helm 3.3.4, Kubernetes 1.18.8

**Which chart?**

name: nri-bundle
version: 1.9.1

**How to reproduce it?**

Deploy with Windows infrastructure support. This was the config we were using:
```
newrelic-infrastructure:
  enableWindows: true
  privileged: true
  nodeSelector:
    kubernetes.io/os: linux
  windowsNodeSelector:
    kubernetes.io/os: windows
```
