### ISSUE TITLE
[newrelic-logging] global.licenseKey set different ENDPOINT and METRICS_HOST then global.customSecretName & global.customSecretLicenseKey

### ISSUE THREAD

**Issue by KlockiLego** [newrelic/helm-charts#1599]
Configuration:

```
newrelic-logging:
  enabled: true
```

```
global:
  licenseKey: "xxxx"
```

OR

```
global:
  customSecretName: "secret_name"
  customSecretLicenseKey: "key_name"
```

The bug is that depending on the method used to pass the key, ENV will be set accordingly. ( METRICS_HOST and ENDPOINT)
This causes a problem with saving logs in New Relic when I want to use customSecretName & customSecretLicenseKey.

`level=error msg="Unexpected non-retryable error received. Logs were discarded." error="received non-2XX HTTP status code: 403`

output from helm diff:

```
newrelic, newrelic-bundle-newrelic-logging, DaemonSet (apps) has changed:
  # Source: nri-bundle/charts/newrelic-logging/templates/daemonset.yaml
  apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    namespace: newrelic
    labels:     
      app: newrelic-logging
      chart: newrelic-logging-1.23.5
      heritage: Helm
      release: newrelic-bundle
      app.kubernetes.io/name: newrelic-logging
    name: newrelic-bundle-newrelic-logging
    annotations:
  spec:
    updateStrategy:
      type: RollingUpdate
    selector:
      matchLabels:
        app: newrelic-logging
        release: newrelic-bundle
    template:
      metadata:
        annotations:
          checksum/fluent-bit-config: ac7d8cfa4d5cb8fbcf67a2e157af619c5a9e7784d08eb2394525aac3d596b2fc
        labels:
          app: newrelic-logging
          release: newrelic-bundle
          kubernetes.io/os: linux
          app.kubernetes.io/name: newrelic-logging
      spec:
        serviceAccountName: newrelic-bundle-newrelic-logging
        dnsPolicy: ClusterFirstWithHostNet
        terminationGracePeriodSeconds: 10
        initContainers:
        containers:
          - name: newrelic-logging
            image: "newrelic/newrelic-fluentbit-output:2.1.0"
            imagePullPolicy: "IfNotPresent"
            env:
              - name: ENDPOINT
-               value: "https://log-api.newrelic.com/log/v1"
+               value: "https://log-api.eu.newrelic.com/log/v1"
              - name: SOURCE
                value:  "kubernetes"
              - name: LICENSE_KEY
                valueFrom:
                  secretKeyRef:
-                   name: secret_name
-                   key: key_name
+                   name: newrelic-bundle-newrelic-logging-config
+                   key: license
              - name: CLUSTER_NAME
                value: cluster_name_xxx
              - name: LOG_LEVEL
                value: "info"
              - name: LOG_PARSER
                value: "cri,docker"
              # NODE_NAME needs to be defined before FB_DB, because FB_DB references NODE_NAME in its value when using persistentVolume
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              - name: FB_DB
                value: "/var/log/flb_kube.db"
              - name: PATH
                value: "/var/log/containers/*.log"
              - name: K8S_BUFFER_SIZE
                value: "32k"
              - name: K8S_LOGGING_EXCLUDE
                value: "false"
              - name: LOW_DATA_MODE
                value: "false"
              - name: RETRY_LIMIT
                value: "5"
              - name: HOSTNAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: SEND_OUTPUT_PLUGIN_METRICS
                value: "false"
              - name: METRICS_HOST
-               value: "metric-api.newrelic.com"
+               value: "metric-api.eu.newrelic.com"
              
            command:
              - /fluent-bit/bin/fluent-bit
              - -c
              - /fluent-bit/etc/fluent-bit.conf
              - -e
              - /fluent-bit/bin/out_newrelic.so
            volumeMounts:
              - name: fluent-bit-config
                mountPath: /fluent-bit/etc
              - name: logs
                # We mount /var by default because container logs could be on /var/log or /var/lib/docker/containers (symlinked to /var/log)
                mountPath: /var
            resources:
              limits:
                cpu: 500m
                memory: 128Mi
              requests:
                cpu: 250m
                memory: 64Mi
        volumes:
          - name: fluent-bit-config
            configMap:
              name: newrelic-bundle-newrelic-logging-fluent-bit-config
          - name: logs
            hostPath:
              path: /var
        nodeSelector:
        tolerations:
          - effect: NoSchedule
            operator: Exists
          - effect: NoExecute
            operator: Exists
newrelic, newrelic-bundle-newrelic-logging-config, Secret (v1) has been added:
+ # Source: nri-bundle/charts/newrelic-logging/templates/secret.yaml
+ apiVersion: v1
+ kind: Secret
+ metadata:
+   labels:
+     app: newrelic-logging
+     app.kubernetes.io/name: newrelic-logging
+     chart: newrelic-logging-1.23.5
+     heritage: Helm
+     release: newrelic-bundle
+   name: newrelic-bundle-newrelic-logging-config
+   namespace: newrelic
+ data:
+   license: '++++++++ # (40 bytes)'
+ type: Opaque

```
