### ISSUE TITLE
[nri-bundle] Helm Upgrade Fails w/ TLS Failed to Verify Certificate

### ISSUE THREAD

**Issue by ben851** [newrelic/helm-charts#1712]
**Bug description**

We are using helmfile to manage our EKS environment. When doing a global helmfile apply after the initial install of the NRI-Bundle chart, the caBundles are reporting as changed. When this happens, we intermittently receive this error

```STDERR:
  Error: UPGRADE FAILED: could not get information about the resource: conversion webhook for 
newrelic.com/v1beta1, Kind=Instrumentation failed: Post "[https://newrelic-k8s-agents-operator-webhook-
service.newrelic.svc:443/convert?timeout=30s](https://newrelic-k8s-agents-operator-webhook-
service.newrelic.svc/convert?timeout=30s)": tls: failed to verify certificate: x509: certificate signed by 
unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate 
authority certificate "k8s-agents-operator-operator-ca")
```

If we re-run the apply it will work. 

Is there a way to "lock in" the caBundle so that it's not always reporting as changed? I suspect that would solve this issue

**Version of Helm and Kubernetes**

EKS 1.32
Helmfile 0.171.0
Helm 3.17.3

**Which chart?**

nri-bundle chart, latest

**What happened?**

Helmfile Apply fails with invalid TLS certificate

**What you expected to happen?**

Ideally, since there are no changes happening on the New Relic chart, the CABundle should not be changed. If that's not possible, then the chart should be able to gracefully upgrade the caBundle without failing

**How to reproduce it?**

Steps to reproduce the problem, as minimally and precisely as possible.

**Anything else we need to know?**

Surprise us!

**Comment by DHI-TommyC** [comment]
I am getting a similar error when trying to update an `Instrumentation` Yaml object. I've tried installing the chart with Helm v3 and v4 with the same result.

when I run `kubectl apply` with the yaml, I get this:
```
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "minstrumentation-v1beta3.kb.io": failed to call webhook: Post "https://newrelic-k8s-agents-operator-webhook-service.newrelic.svc:443/mutate-newrelic-com-v1beta3-instrumentation?timeout=10s": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

It looks to be hitting the same Webhook Service that OP has, just a different URL. The Service points to the `newrelic-k8s-agents-operator` pod.

In a test pod in the same namespace, trying to connect to that endpoint with `curl` looks like this:
```
$ curl https://newrelic-k8s-agents-operator-webhook-service.newrelic.svc:443/
curl: (60) SSL certificate problem: unable to get local issuer certificate
```
and I tried to get the certificate itself to see if I could identify the problem with it, I tried with `openssl`:
```
$ openssl s_client -showcerts -servername newrelic-k8s-agents-operator-webhook-service.newrelic.svc -connect newrelic-k8s-agents-operator-webhook-service.newrelic.svc:443 <<< "Q" | openssl x509 -text
Connecting to 10.96.132.242
depth=0 CN=newrelic-k8s-agents-operator
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN=newrelic-k8s-agents-operator
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 CN=newrelic-k8s-agents-operator
verify return:1
DONE
```
In the certificate text output, it shows that it's issued by `k8s-agents-operator-operator-ca`, which looks self-signed to me, and is supported by the comments in the `values.yml` for the [k8s-agents-operator chart](https://github.com/newrelic/k8s-agents-operator/blob/main/charts/k8s-agents-operator/values.yaml) in lines 147-172.

Here is the yaml I'm trying to apply:
```yaml
apiVersion: newrelic.com/v1beta3
kind: Instrumentation
metadata:
  name: newrelic-instrumentation-dotnet
  namespace: newrelic
spec:
  agent:
    language: dotnet
    image: harbor.repo.local/docker/newrelic/newrelic-dotnet-init:latest
    env:
      - name: NEW_RELIC_APP_NAME
        value: "$(Serilog__Properties__Application)-$(Serilog__Properties__Environment)"
  namespaceLabelSelector:
    matchExpressions:
      - key: "nrapm"
        operator: "In"
        values: ["enabled"]
```
