### ISSUE TITLE
[newrelic-infrastructure] doesn't reload its own ConfigMap

### ISSUE THREAD

**Issue by freehck-codefresh** [newrelic/helm-charts#240]
**Bug description**

subj
newrelic-infrastructure doesn't reload its configuration

**Version of Helm and Kubernetes**

```
% helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
% kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-gke.4300", GitCommit:"7ed5ddc0e67cb68296994f0b754cec45450d6a64", GitTreeState:"clean", BuildDate:"2020-10-28T09:23:22Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart?**
```
% helm list | grep newrelic-infrastructure
newrelic-infrastructure	newrelic 	1       	2020-12-14 10:18:01.137575 +0300 MSK	deployed	newrelic-infrastructure-1.6.5	1.26.8
```

**What happened?**

I fed the newrelic-infrastructure chart with a following config (templated by gotmpl as I use helmfile, but it'll give some basic understanding / labels and so on were substituted):

```
% cat newrelic-infrastructure.yaml.gotmpl
USER-SUPPLIED VALUES:
cluster: "{{ .Values.cluster_name }}"
config:
  custom_attributes:
    cluster: "{{ .Values.cluster_name }}"
licenseKey: "{{ .Values.nri_license_key }}"
integrations_config:
  - name: nri-redis.yaml
    data:
      discovery:
        command:
          exec: /var/db/newrelic-infra/nri-discovery-kubernetes
          match:
            label.app: redis
      integrations:
        - name: nri-redis
          env:
            HOSTNAME: ${discovery.ip}
            PORT: 6379
            PASSWORD: "{{ .Values.redis_pass }}"
          labels:
            env: "{{ .Values.cluster_name }}"
            role: redis
  - name: nri-rabbitmq.yaml
    data:
      discovery:
        command:
          exec: /var/db/newrelic-infra/nri-discovery-kubernetes
          match:
            label.app: rabbit
      integrations:
        - name: nri-rabbitmq
          env:
            HOSTNAME: ${discovery.ip}
            PORT: 15672
            USERNAME: "{{ .Values.rabbitmq_user }}"
            PASSWORD: "{{ .Values.rabbitmq_pass }}"
          labels:
            env: "{{ .Values.cluster_name }}"
            role: rabbitmq
```

Applied the chart to my cluster with these values. Went to the UI, started to see rabbitmq and redis metrics. Then decided to add a block for postgresql. Kind of:
```
<...>
  - name: postgresql.yaml
    data:
      integration_name: com.newrelic.postgresql
      instances:
        - name: production-postgres
          command: all_data
          arguments:
            username: "{{ .Values.postgres_username }}"
            password: "{{ .Values.postgres_password }}"
            hostname: "{{ .Values.postgres_host }}"
            port: {{ .Values.postgres_port }}
            collection_list: '["dbname"]'
            collect_db_lock_metrics: false
            timeout: {{ .Values.postgres_nri_scrape_timeout }}
          labels:
            env: "{{ .Values.cluster_name }}"
            role: postgresql
```
Updated chart with these values. Went to the UI, didn't find any postgresql metrics at all. Waited for an hour -- w/o any result.
Deleted the chart completely and applied it again. Started to see postgresql metrics immediately.

As all the changes related to the ConfigMap, it's clear now that newrelic-infrastructure doesn't reload its own configuration.

**What you expected to happen?**

Expected the config to be reloaded. To see postgresql metrics in the UI with all the other metrics.

**Comment by freehck-codefresh** [comment]
Found that this workaround works:
```
podAnnotations:
   checksum/config: {{ tpl "configmap.yaml" . | sha256sum }}
 ```

**Comment by freehck-codefresh** [comment]
I mean, it works it we put it into the `values.yaml`.
Feel free to use it as a default or as one of the possible solutions.

**Comment by invidian** [comment]
It seems to me that idea with annotation with config checksum is a good way to resolve this.

**Comment by gauravgola96** [comment]
@freehck-codefresh @invidian i am trying to achieve integration host for redis. I commented out intergations_config part for redis is values.yaml
And deployed with `helm upgrade --reuse-values values.yaml newrelic-bundle newrelic/nri-bundle`
But i don't see any configmap created and also no metrics

**Comment by gauravgola96** [comment]
@invidian @freehck-codefresh I have also tried yaml manifest
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-integration-cfg
  namespace: newrelic
data:
  redis-config.yml: |
    ---
    # Run auto discovery to find pods with label "app=redis"
    # https://docs.newrelic.com/docs/integrations/host-integrations/installation/container-auto-discovery
    discovery:
      command:
        # Use the following optional arguments:
        # --namespaces: Comma separated list of namespaces to discover pods on
        # --tls: Use secure (TLS) connection
        # --port: Port used to connect to the kubelet. Default is 10255
        exec: /var/db/newrelic-infra/nri-discovery-kubernetes --namespaces redis --tls --port 10250
        match:
          label.app: redis
    integrations:
      - name: nri-redis
        env:
          # using the discovered IP as the hostname address
          HOSTNAME: ${discovery.ip}
          PORT: 6379
          PASSWORD: '***'
          REMOTE_MONITORING: true
          use_unix_socket: true
        labels:
              type: cache
              env: staging
```
and mounted volume in newrelic-infra daemonset as well 
```
 volumeMounts:
            - name: dev
              mountPath: /dev
            - name: host-docker-socket
              mountPath: /var/run/docker.sock
            - name: log
              mountPath: /var/log
            - name: host-volume
              mountPath: /host
              readOnly: true
            - name: integration-config
              mountPath: /etc/newrelic-infra/redis-config.yml
              subPath: redis-config.yml
          resources:
            limits:
              memory: 300M
            requests:
              cpu: 100m
              memory: 150M
            
      volumes:
        - name: dev
          hostPath:
            path: /dev
        - name: host-docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: log
          hostPath:
            path: /var/log
        - name: host-volume
          hostPath:
            path: /
        - name: integration-config
          configMap:
            name: nri-integration-cfg
```

when i checked in pod log 
./nri-redist throws` [FATAL] can't continue: Redis connection through TCP failed, got error: dial tcp 192.168.1.41:6379: connect: connection refused
`

but i manually run it with 
`./nri-redis -hostname redis-master.redis.svc.cluster.local -port 6379 -password '***'` 
it connects 
any help is really appreciated !
