### ISSUE TITLE
[newrelic-infrastructure] Bug when trying to configure kubernetes scraping interval

### ISSUE THREAD

**Issue by fr-ser** [newrelic/helm-charts#344]
**Bug description**

I was trying to use the `integrations_config` config value to specify a higher scraping interval, than the default 15 seconds.
This was not possible. In addition, I started encountering the behavior of all metrics being reported twice

**Which chart?**
- chart name: newrelic-infrastructure
- chart: 2.4.1
- app: 2.4.0

**What happened?**

This was the value applied:

```yaml
integrations_config:
    - name: nri-kubernetes-config.yml
      data:
        integration_name: com.newrelic.kubernetes
        instances:
            - name: nri-kubernetes
              command: metrics
              interval: 60
```

As a result, I was receiving all metrics **still every 15 seconds** but now I was **receiving them all twice**
This was found by using this NRQL query:
```txt
select * from K8sContainerSample where clusterName = 'data-intelligence-staging' and entityGuid ='MjI1ODEwNXxJTkZSQXxOQXw0MDEwMjcyNjc5NDU0MTUzMTQ2' since 5 minutes ago
```
There I could see that for a single entity I had two values now every 15 seconds.

**What you expected to happen?**

I receive the values once but only every 60 seconds.
