### ISSUE TITLE
[nri-metadata-injection] <Not seeing default namespace in cluster explorer>

### ISSUE THREAD

**Issue by mcandio** [newrelic/helm-charts#351]
**Bug description**

**Version of Helm and Kubernetes**

Kubernete version: 1.18

Helm version: version.BuildInfo{Version:"v3.5.4"

**Which chart?**

nri-bundle

**What happened?**

I'm not able to fetch resource utilization for my deployments in my default namespace, the metadata injector is not putting any env in the pods, so when I want to watch the deployments and the namespace in cluster explorer, default does not appear.

I'm using terraform 0.15 with helmfile provider by mumoshu with parameter Working directory but the problem appears even if I install the chart manually.
The K8s cluster is running in EKS.
I tested creating a new namespace and deploying a simple nginx pod and this is working fine.
If I use 'webhook.injectOnlyLabeledNamespaces: true'  (with the default namespace labeled: newrelic-metadata-injection=enabled )the chart does not recognize this as a change (may be template parsing?)

Im deploying with privileged mode

Is there any option that I am missing?

**What you expected to happen?**

Default namespace should show metrics in cluster explorer

**How to reproduce it?**

Just deploy the helmchart just like this: 

helm repo add newrelic https://helm-charts.newrelic.com && \
kubectl create namespace monitoring ; helm install newrelic-bundle newrelic/nri-bundle \
 --set global.licenseKey=$LICENSEKEY \
 --set global.cluster=$CLUSTERNAME \
 --namespace=monitoring \
 --set newrelic-infrastructure.privileged=true \
 --set ksm.enabled=true \
 --set prometheus.enabled=true \
 --set kubeEvents.enabled=true \
 --set logging.enabled=false 

and be sure to put some deployment in default namespace

kubectl apply -f https://k8s.io/examples/application/deployment.yaml

Hope you can help me understand if this behavior is corerct.

**Comment by mcandio** [comment]
I also tested changing the injectOnlyLabeledNamespaces outside valued.global, inside values.global as well as values.webhook.injectOnlyLabeledNamespaces

```
repositories:
  - name: newrelic
    url: https://helm-charts.newrelic.com
helmDefaults:
  wait: true
  timeout: 600
  atomic: false
  kubeContext: {{ requiredEnv "KUBECTX" }}
releases:
  - name: newrelic
    namespace:  {{ requiredEnv "NAMESPACE" }}
    chart: newrelic/nri-bundle
    labels:
      environment: {{ requiredEnv "ENVIRONMENT" }}
    values:
      - injectOnlyLabeledNamespaces: true
      - global:
          fargate: true
          licenseKey: {{requiredEnv "NEWRELIC_LICENSE_KEY" | quote}}
          cluster: {{requiredEnv "CLUSTER_NAME"}}
          injectOnlyLabeledNamespaces: true
        newrelic-infrastructure:
          priviledged: true
          enableProcessMetrics: true
          
        webhook:
          enabled: {{ env "WEBHOOK_ENABLED" | default true }}

         ksm:
          enabled: {{ env "KSM_ENABLED" | default true }}

        prometheus:
          enabled: {{ env "PROMETHEUS_ENABLED" | default true }}

        kubeEvents:
          enabled: {{ env "KUBEEVENTS_ENABLED" | default true }}

        logging:
          enabled: {{ env "LOGGING_ENABLED" | default false }}
```
Where do I need to put  "injectOnlyLabeledNamespaces: true" ? 
According to this [file](https://github.com/newrelic/helm-charts/blob/master/charts/nri-metadata-injection/templates/admission-webhooks/mutatingWebhookConfiguration.yaml) this should be at: webhook. injectOnlyLabeledNamespaces right?
