### ISSUE TITLE
[nri-kube-events] Duplicate imagePullPolicy

### ISSUE THREAD

**Issue by DWSR** [newrelic/helm-charts#407]
**Bug description**

`imagePullPolicy` is defined twice in one of the container definitions: https://github.com/newrelic/helm-charts/blob/d942ed5b85ea693c937e0fdd05a1a90a4bbd0067/charts/nri-kube-events/templates/deployment.yaml#L37-L46

**Version of Helm and Kubernetes**

Helm: Any version
Kubernetes: Doesn't matter

**Which chart?**

`nri-kube-events` 1.9.2

**What happened?**

Ran `helm template` and got back invalid YAML.

**What you expected to happen?**

Running `helm template` should produce valid YAML

**How to reproduce it?**

Using the following `values.yaml`:

```yaml
kubeEvents:
  enabled: true

global:
  customSecretName: "newrelic-api-keys"
  customSecretLicenseKey: "license-key"
  customSecretInsightsKey: "insights-key"
  cluster: "CLUSTER_NAME"
```

Run `helm template newrelic newrelic/nri-bundle --values values.yaml`

**Anything else we need to know?**

I would love Kustomize applications instead of Helm charts for exactly reasons like this. :)
