### ISSUE TITLE
[nri-metadata-injection] Duplicate restartPolicy

### ISSUE THREAD

**Issue by DWSR** [newrelic/helm-charts#408]
**Bug description**

The `restartPolicy` key is present twice on a job in the `nri-metadata-injection` chart: https://github.com/newrelic/helm-charts/blob/master/charts/nri-metadata-injection/templates/admission-webhooks/job-patch/job-createSecret.yaml#L36-L41

**Version of Helm and Kubernetes**

Helm: Doesn't matter
Kubernetes: Doesn't matter

**Which chart?**

`nri-metadata-injection` 1.5.0

**What happened?**

Ran `helm template` and got back invalid YAML

**What you expected to happen?**

Running `helm template` should result in valid YAML

**How to reproduce it?**

Using the following `values.yaml`:

```yaml
webhook:
  enabled: true

global:
  customSecretName: "newrelic-api-keys"
  customSecretLicenseKey: "license-key"
  customSecretInsightsKey: "insights-key"
  cluster: "CLUSTER_NAME"
```

Run `helm template newrelic newrelic/nri-bundle --values values.yaml`

**Anything else we need to know?**

Please just release Kustomize applications instead of using Helm.
