### ISSUE TITLE
[newrelic-infrastructure] Oracle kuberentes engine logging not picked up automatically (with solution for PR attached)

### ISSUE THREAD

**Issue by PeterMerkert** [newrelic/helm-charts#434]
**Bug description**

Executing New Relic manifest on Oracle Kuberentes Engine will not transmit logs.

**Version of Helm and Kubernetes**

Affecting all versions.
Also latest 1.5.0.

Oracle Kuberentes Engine any version.
Also Oracle Kuberentes Engine latest version v1.19.12.

**Which chart?**

It is the file: `nri-bundle/charts/newrelic-infrastructure/templates/daemonset.yaml`

**What happened?**

Executing the manifest in Oracle Kubernetes Engine will work smoothly without problems. However, New Relic dashboard will show that no logs are transmitted from the cluster. It does show the "Install now to get logs" screen.
All other pages are filled with statistics about compute instances and details of the cluster. However, the log screen will stay empty.

**What you expected to happen?**

The logs are fetched automatically from Oracle Kubernetes Engine.

**How to reproduce it?**

Start an Oracle Kuberentes Engine in Oracle Cloud Infrastructure. Then execute the manifest of New Relic into kubernetes.

**Anything else we need to know?**

The problem here is that apparently in Oracle the logs are stored in an unconventional location: `/u01/data/docker/containers`. I had the same problem when using [LogDNA](https://www.logdna.com/) cloud logging solution. I commented on a [PR with a similar case](https://github.com/logdna/logdna-agent/pull/107).

I am not an expert how to modify the helm-charts and cannot provide a PR, but the following file is working with Oracle Kubernetes Engine.

<details><summary>A working example of newrelic-logging/templates/daemonset.yaml</summary>
<p>

Have a look at the two volumneMounts and volumes with `/u01/data/docker/containers` as paths.

```
# Source: nri-bundle/charts/newrelic-logging/templates/daemonset.yaml

apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: newrelic
  labels:
    app: newrelic-logging
    chart: newrelic-logging-1.4.8
    release: nri-bundle
    app.kubernetes.io/name: newrelic-logging
  name: nri-bundle-newrelic-logging
  annotations:
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: newrelic-logging
      release: nri-bundle
  template:
    metadata:
      labels:
        app: newrelic-logging
        release: nri-bundle
        app.kubernetes.io/name: newrelic-logging
    spec:
      serviceAccountName: nri-bundle-newrelic-logging
      hostNetwork: true # This option is a requirement for the Infrastructure Agent to report the proper hostname in New Relic.
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 10
      containers:
        - name: newrelic-logging
          image: "newrelic/newrelic-fluentbit-output:1.4.6"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: ENDPOINT
              value: "https://log-api.eu.newrelic.com/log/v1"
            - name: SOURCE
              value: "kubernetes"
            - name: LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: nri-bundle-newrelic-logging-config
                  key: license
            - name: CLUSTER_NAME
              value: Production
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_PARSER
              value: "docker"
            - name: PATH
              value: "/var/log/containers/*.log"
            - name: K8S_LOGGING_EXCLUDE
              value: "Off"
          command:
            - /fluent-bit/bin/fluent-bit
            - -c
            - /fluent-bit/etc/fluent-bit.conf
            - -e
            - /fluent-bit/bin/out_newrelic.so
          volumeMounts:
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc
            - name: var
              mountPath: /var
            - name: oke
              mountPath: /u01/data/docker/containers
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi

      volumes:
        - name: fluent-bit-config
          configMap:
            name: nri-bundle-newrelic-logging-fluent-bit-config
        - name: var
          hostPath:
            path: /var
        - name: oke
          hostPath:
            path: /u01/data/docker/containers
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
```
</p>
</details>

Hope this helps to also provide support for Oracle Kubernetes Engine.
