### ISSUE TITLE
[nri-metadata-injection] Add support for pullSecrets for all images

### ISSUE THREAD

**Issue by esteban1983cl** [newrelic/helm-charts#460]
**Is your feature request related to a problem? Please describe.**

Hi currently due docker pull limits I can't do pull for some images:

```yaml
jobImage:
  # repository: jettech/kube-webhook-certgen
  repository: registry.example.com/jettech/kube-webhook-certgen
  tag: v1.5.0
  pullPolicy: IfNotPresent
  # Volume mounts to add to the job, you might want to mount tmp if Pod Security Policies
  # Enforce a read-only root.
  volumeMounts: []
  #  - name: tmp
  #    mountPath: /tmp

  # Volumes to add to the job container
  volumes: []
  #  - name: tmp
  #    emptyDir: {}
```

**Describe the solution you'd like**

I need support for add pullSecrets section in jobImage

```yaml
jobImage:
  # repository: jettech/kube-webhook-certgen
  repository: registry.example.com/jettech/kube-webhook-certgen
  tag: v1.5.0
  pullPolicy: IfNotPresent
  pullSecrets:
  - mypull-secret
  # Volume mounts to add to the job, you might want to mount tmp if Pod Security Policies
  # Enforce a read-only root.
  volumeMounts: []
  #  - name: tmp
  #    mountPath: /tmp

  # Volumes to add to the job container
  volumes: []
  #  - name: tmp
  #    emptyDir: {}
```

**Describe alternatives you've considered**

Move your images to quay.io maybe

**Additional context**

Nothing else
