### ISSUE TITLE
How to supply YAML values for licenseKey and apiKey for newrelic-pixie (in nri-bundle)

### ISSUE THREAD

**Issue by andrewhearin** [newrelic/helm-charts#557]
Hi all, I will try to make this as brief as I can, apologies if this is way easier than I'm making it! Hopefully just a simple syntax fix.

I'm trying to spin up the pixie integration in the nri-bundle 3.2.1 via helm to a cluster in GKE.

According to the documentation, **licenseKey** and **apiKey** are both required.  I've also found that the my **nri-bundle-newrelic-pixie-secrets** secret is never created if I do not supply both licenseKey and apiKey.

I am storing my licenseKey and apiKey in gcpSecretsManager and using kubernetes-external-secrets to make them accessible
https://github.com/external-secrets/kubernetes-external-secrets

which works fine and the key is stored.

My problem is, in my YAML, how do I supply the value from the secret, to **licenseKey** and **apiKey**?
I would assume it is some nested format but I am just not sure how to do it.

(works fine if I simply assign the licenseid, api key in quotes, but trying to keep these in secret manager)

When I try to do something such as 
```yaml
    licenseKey:
      name: newrelic-license
      key: license-key
    apiKey:
      name: newrelic-license
      key: api-key
```

when I describe the secret, these values, the decoded values are just the attempted maps, not the password for each itself.

```yaml
❯ kubectl get secret nri-bundle-newrelic-pixie-secrets -n nri-bundle -o yaml
apiVersion: v1
data:
  newrelicLicenseKey: bWFwW2tleTpsaWNlbnNlLWtleSBuYW1lOm5ld3JlbGljLWxpY2Vuc2Vd
  pixieApiKey: bWFwW2tleTphcGkta2V5IG5hbWU6bmV3cmVsaWMtbGljZW5zZV0=
```
the above returns: "map[key:license-key name:newrelic-license]" when decoded.

and if I simply tried attaching the name of the secret itself like:
```yaml
licenseKey: license-key
apiKey: api-key
```
that text just gets base64 encoded instead.

My sample helm deployment looks like the below currently:

```yaml
name: redacted
nri-bundle:
  global:
    cluster: my-cluster
  newrelic-pixie:
    enabled: true
    licenseKey:
    apiKey:
  pixie-chart:
    enabled: true
    deployKey: "px-dep-123456"
    
externalSecret:
  spec:
    backendType: gcpSecretsManager
    data:
      - key: my-cluster-nri-bundle_newrelic-license
        name: license-key    
      - key: my-cluster-nri-bundle_pixie_api_key
        name: api-key
```

If it helps, this is my separate kubernetes-external-secrets yaml:
```yaml
{{- if .Values.externalSecret }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: newrelic-license
{{ toYaml $.Values.externalSecret }}
{{- end}}
```

The other thing I tried was looking at the helpers.tpl, and this conditional statement, thinking I may be able to just supply the customSecret* parameters.
https://github.com/newrelic/helm-charts/blob/master/charts/newrelic-pixie/templates/_helpers.tpl#L153

and tried supplying information as:
```yaml
  newrelic-pixie:
    enabled: true
    customSecretName: newrelic-license
    customSecretLicenseKey: key
    customSecretApiKeyName: api-key
    customSecretApiKeyKey: key
```
However, when I supply the above, the pixie-secret is never created, and the pod is never able to authenticate. It seems that licenseKey and apiKey are indeed required, to get this secret going and everything working properly.

Just a final note that:
      - key: my-cluster-nri-bundle_newrelic-license
        name: license-key    
      - key: my-cluster-nri-bundle_pixie_api_key
        name: api-key

The above keys / values exist in gcpSecrets manager and is visible as a secret. I just don't know how to tie these values to a single parameter for licenseKey and apiKey respectively so my pods come up correctly

Thank you in advance!

**Comment by andrewhearin** [comment]
I'd actually like to re-open this, as I am curious if / how others are accessing secret values stored in secret managers (aws parameter store, gcpSecretsManager) and assigning them for:

**licenseKey**
**apiKey**
 **deployKey**

I think part of the problem is that with the following:
```yaml
    customSecretName: newrelic-license
    customSecretLicenseKey: key
    customSecretApiKeyName: api-key
    customSecretApiKeyKey: key
```

It allows you to reference a Secret Object and a Secret Value


with these:
**licenseKey**
**apiKey**
 **deployKey**

I am not sure how to do the same, so for now I am resulting to hard-coding my **deployKey** in my deployment
