### ISSUE TITLE
[nri-infrastructure] Reduce DNS load on the K8 clusters

### ISSUE THREAD

**Issue by jodem** [newrelic/helm-charts#589]
**Is your feature request related to a problem? Please describe.**

On my EKS cluster I see newrelic to be the n#1 DNS request issuer. By default when doing a DNS query on "infra-api.newrelic.com", coreDNS will try to resolve it in different context :
* infra-api.newrelic.com.eu-west-1.compute.internal.
* infra-api.newrelic.com.cluster.local
* infra-api.newrelic.com.svc.cluster.local.
* infra-api.newrelic.com.newrelic.svc.cluster.local.

Finally it's able to understand that the pod is not asking for a local address but for api.newrelic.com public one. So each time a pod is doing a DNS query to newrelic, it goes through 5 errors in the DNS resolution before finding the good one.

Since newrelic is using multiple endpoints (intra, indentity, metric), multiplied by the number of hosts and the frequency of theses requests, you end up with hundread thousands of DNS request per day for nothing. 

**Describe the solution you'd like**

One solution could be to use only fully qualified domain name (FQDN) like **infra-api.newrelic.com.** (mind the tailing dot), or add an option to override the default newrelic endpoint.

**Describe alternatives you've considered**

Another option would be to allow us setting the NDOT setting of the deamonset :
``` yaml 

dnsConfig:
    options:
      - name: ndots
        value: '1'
```

> ndots sets a threshold for the number of dots which must appear in a name before an initial absolute query will be made. The default for n is 1, meaning that if there are any dots in a name, the name will be tried first as an absolute name before any search list elements are appended to it.

**Additional context**

A good article about FQDN kube and DNS : https://pracucci.com/kubernetes-dns-resolution-ndots-options-and-why-it-may-affect-application-performances.html

**Comment by roobre** [comment]
Hi!

We're still working on figuring the possible impact of changing the defaults for the infra-agent so they include the trailing dot.

In the meantime, as a workaround, these endpoints can actually be overridden by the user. Please take a look [here](https://github.com/newrelic/infrastructure-agent/blob/master/pkg/config/config.go#L79-L109), where you can see the default value and the name of the yaml property that is mapped to it. The place to specify these keys would be under the [`config` entry of the `newrelic-infrastructure` chart](https://github.com/newrelic/helm-charts/blob/0eaba78a2b2e427ba15648f888bd7b35d318330c/charts/newrelic-infrastructure/values.yaml#L148).

**Comment by jodem** [comment]
Hi @roobre , sounds like a good workaround indeed. Thanks.

**Comment by kang-makes** [comment]
The common library implements `dnsConfig` but we still have to adapt all the helm charts to use it. Github autoclosed this but this is still an issue.

**Comment by kang-makes** [comment]
This should be fixed with the latest version of the charts that implement the `common-library` chart:

| Global keys | Local keys | Default | Merged[<sup>1</sup>](https://github.com/newrelic/helm-charts/tree/master/library/common-library#values-managed-globally-1) | Description |
|---|---|---|---|---
| global.dnsConfig | dnsConfig | `{}` |  | Sets pod's dnsConfig |

**Comment by immae1** [comment]
Hi @kang-makes , could it be that the newrelic-logging subchart is the only chart where the `global.dnsConfig` value is not applied?

I used the following values.yaml:

```yaml
global:
  customSecretName: newrelic-license-key
  customSecretLicenseKey: license_key
  dnsConfig:
    options:
      - name: ndots
        value: '1'
  cluster: "test"        
pixie-chart:
  enabled: false 

kube-state-metrics:
  # kube-state-metrics.enabled -- Install the [`kube-state-metrics` chart](https://github.com/kubernetes/kube-state-metrics/tree/master/charts/kube-state-metrics) from the stable helm charts repository.
  # This is mandatory if `infrastructure.enabled` is set to `true` and the user does not provide its own instance of KSM version >=1.8 and <=2.0
  enabled: true

newrelic-infrastructure:
  enable: true

newrelic-logging:
  enabled: true
  fluentBit:
    logLevel: "info"
    path: "/var/log/containers/*.log"
```
When I render the pulled nri-bundle table locally with helm template like this: `helm template -f newrelic-bundle/values.yaml nri-bundle --debug` I see that all deployments/daemosets set the spec dnsConfigkey. For example, see the kublet daemonset deployment below:

```yaml
# Source: nri-bundle/charts/newrelic-infrastructure/templates/kubelet/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: newrelic
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: newrelic-infrastructure
    app.kubernetes.io/version: 3.15.1
    helm.sh/chart: newrelic-infrastructure-3.20.1
    mode: privileged
  name: release-name-nrk8s-kubelet
spec:
  updateStrategy: 
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: newrelic-infrastructure
      app.kubernetes.io/component: kubelet
  template:
    metadata:
      annotations:.
      ...
      labels:
        ...
        app.kubernetes.io/component: kubelet
    spec:
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      serviceAccountName: release-name-newrelic-infrastructure
      hostNetwork: false
      containers:
        - name: kubelet
```

But the newrelic-logging deployment (fluent-bit output pod) will not get the dnsConfig from global key as you can see here:

```yaml
# Source: nri-bundle/charts/newrelic-logging/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: newrelic
  labels:     
    app: newrelic-logging
    chart: newrelic-logging-1.14.2
    heritage: Helm
    release: release-name
    app.kubernetes.io/name: newrelic-logging
  name: release-name-newrelic-logging
  annotations:
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: newrelic-logging
      release: release-name
  template:
    metadata:
      annotations:
       ...
      labels:
        ...
    spec:
      serviceAccountName: release-name-newrelic-logging
      hostNetwork: true # This option is a requirement for the Infrastructure Agent to report the proper hostname in New Relic.
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 10
      containers:
        - name: newrelic-logging
          image: "newrelic/newrelic-fluentbit-output:1.16.0"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: ENDPOINT
              value: "https://log-api.newrelic.com/log/v1"
            - name: SOURCE
              value:  "kubernetes"
            - name: LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: newrelic-license-key
                  key: license_key
            - name: CLUSTER_NAME
              value: test
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_PARSER
              value: "docker"
            - name: FB_DB
              value: "/var/log/flb_kube.db"
            - name: PATH
              value: "/var/log/containers/*.log"
            - name: K8S_BUFFER_SIZE
              value: "32k"
            - name: K8S_LOGGING_EXCLUDE
              value: "Off"
            - name: LOW_DATA_MODE
              value: "false"
            - name: RETRY_LIMIT
              value: "5"
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            
          command:
            - /fluent-bit/bin/fluent-bit
            - -c
            - /fluent-bit/etc/fluent-bit.conf
            - -e
            - /fluent-bit/bin/out_newrelic.so
          volumeMounts:
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc
            - name: var
              mountPath: /var
          resources:
            limits:
              cpu: 700m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 64Mi
      volumes:
        - name: fluent-bit-config
          configMap:
            name: release-name-newrelic-logging-fluent-bit-config
        - name: var
          hostPath:
            path: /var
      nodeSelector:
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
        - effect: NoSchedule
          key: CriticalAddonsOnly
          operator: Equal
          value: "true"
```

So my question is why does this deployment not get the dnsConfig? Maybe something was overlooked when adding this feature? Or is the fluentbit image being used incompatible with this dnsConfig? 

I want to set this ntdot value as the newrelic logging pod on my AKS cluster is facing DNS issues like below:
`newrelic-logging [2023/07/26 11:18:40] [ warn] [net] getaddrinfo(host='kubernetes.default.svc.cluster.local', err=-3): Temporary failure in name resolution
newrelic-bundle-nrb-newrelic-logging-gd7wl newrelic-logging [error] [filter:kubernetes:kubernetes.0] kubelet upstream connection error
`
My hope is that setting `ndot = 1` will reduce the amount of DNS requests so that timeouts do not occur again. 

Thanks in advance for your help/replies 
Regards
