### ISSUE TITLE
newrelic-infrastructure-v3: Clarify interaction between privileged mode and control plane monitoring

### ISSUE THREAD

**Issue by roobre** [newrelic/helm-charts#642]
Right now, we have a weird interaction between `privileged` setting and control plane monitoring. This is because, by default, control plane monitoring requires `hostNetwork: true` to run as most CP components listen only on `localhost`.

However, the `privileged` flag controls more things, namely intrusive `hostPath` mounts and privileged agent container, so one could foresee an use case where a user is willing to allow `hostNetwork` to monitor the control plane, but is not fine with privileged containers. This is currently not possible at the moment.

### Proposal

We could have a more fine-grained control of privilege on the chart. For example, in the values.yml, we could do:
```yaml
# -- Enable or disable privileged operations to get access to more detailed metrics
privileges:
  # -- Allow to run the agent as a privileged container to obtain host-level metrics.
  enablePrivilegedContainers: true
  # -- Allow to mount the host root in the agent container to obtain host-level metrics.
  enableHostNetwork: true
  # -- Allow to use hostNetwork to monitor control plane pods and gather host-level network metrics.
  enableHostPath: true
```

This would supersede the old `privileged` flag, and we would add a shim for it in the compatibility layer.
