### ISSUE TITLE
[nri-bundle] Error: couldn't find key cluster-id in Secret newrelic/pl-cluster-secrets

### ISSUE THREAD

**Issue by luisdavim** [newrelic/helm-charts#661]
**Bug description**

I'm trying to install the nri-bundle-3.3.0 chart using terraform and sometimes, not always, the installation fails because one of the pods fails to start within the wait time set for the helm release.
I'm setting a helm timeout of 900 seconds, and still, sometimes that's not enough...

When I inspect the Pod that is failing to start, I see the following error in its events:

```
Error: couldn't find key cluster-id in Secret newrelic/pl-cluster-secrets
```

If I wait for long enough, it eventually works, a way to speed it up is to delete the failed Pod until it succeeds, but I don't think this is viable, we're usgin Terraform to provision our clusters, and we end up wasting time because of this when it sould be able to run unattended.

**Version of Helm and Kubernetes**

```console
helm version
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}
```

```console
kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-eks-f17b81", GitCommit:"f17b810c9e5a82200d28b6210b458497ddfcf31b", GitTreeState:"clean", BuildDate:"2021-10-15T21:46:21Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart?**

The chart is `nri-bundle-3.3.0`

**What happened?**

The helm release fails, waiting for all the resources to become ready within 900 seconds.

**What you expected to happen?**

I would expect the deployment to succeed, this seems to be some sort of race condition where a secret (`pl-cluster-secrets`) is being created/updated after the pod that needs it to start, so I'd expect that secret to be ready before the deployment is created.
I would also expect 900 seconds to be enough time for any helm release.

**How to reproduce it?**

Just a normal helm install as mentioned in the readme, these are the values I'm using:

```yaml
global:
  cluster: ${clusterName}
  licenseKey: ${newRelicLicenseKey}
  lowDataMode: true
kubeEvents:
  enabled: true
webhook:
  enabled: true
prometheus:
  enabled: true
logging:
  enabled: true
ksm:
  enabled: false
newrelic-infrastructure:
  privileged: true
newrelic-pixie:
  apiKey: ${pixieApiKey}
  enabled: true
pixie-chart:
  clusterName: ${clusterName}
  deployKey: ${pixieChartKey}
  enabled: true
```

**Comment by luisdavim** [comment]
In case this helps, this is the Terraform code we're using to deploy the chart:

```tf
resource "helm_release" "newrelic" {
  count            = var.enable_newrelic ? 1 : 0
  chart            = "nri-bundle"
  name             = "newrelic-bundle"
  repository       = "https://helm-charts.newrelic.com"
  version          = "3.3.0"
  create_namespace = true
  namespace        = "newrelic"
  timeout          = 900
  max_history      = 10

  values = [
    templatefile("${path.module}/templates/values-newrelic.yaml",
      {
        clusterName        = var.cluster_name
        newRelicLicenseKey = local.shared-licences["newrelicLicenseKey"]
        pixieApiKey        = local.shared-licences["newrelicPixieApiKey"]
        pixieChartKey      = local.shared-licences["newrelicPixieChartKey"]
    }),
  ]

  depends_on = [
    kubectl_manifest.pixie-viziers,
    kubectl_manifest.pixie-crd,
  ]
}

resource "kubectl_manifest" "pixie-viziers" {
  count     = var.enable_newrelic ? length(data.kubectl_file_documents.pixie-viziers[0].documents) : 0
  yaml_body = element(data.kubectl_file_documents.pixie-viziers[0].documents, count.index)

  depends_on = [
    null_resource.cluster_up
  ]
}

resource "kubectl_manifest" "pixie-crd" {
  count     = var.enable_newrelic ? length(data.kubectl_file_documents.pixie-crd[0].documents) : 0
  yaml_body = element(data.kubectl_file_documents.pixie-crd[0].documents, count.index)

  depends_on = [
    null_resource.cluster_up
  ]
}

data "kubectl_file_documents" "pixie-viziers" {
  count   = var.enable_newrelic ? 1 : 0
  content = data.http.pixie-viziers[0].body
}

data "kubectl_file_documents" "pixie-crd" {
  count   = var.enable_newrelic ? 1 : 0
  content = data.http.pixie-crd[0].body
}

data "http" "pixie-viziers" {
  count = var.enable_newrelic ? 1 : 0
  url   = "https://raw.githubusercontent.com/pixie-labs/pixie/release/cloud/prod/1642205277/k8s/operator/crd/base/px.dev_viziers.yaml"
}

data "http" "pixie-crd" {
  count = var.enable_newrelic ? 1 : 0
  url   = "https://raw.githubusercontent.com/pixie-labs/pixie/release/cloud/prod/1642205277/k8s/operator/helm/crds/olm_crd.yaml"
}

data "aws_ssm_parameter" "licences" {
  count = var.enable_newrelic ? 1 : 0
  name  = "/shared/licences"
}
```

Where the values file template is:

```yaml
global:
  cluster: ${clusterName}
  licenseKey: ${newRelicLicenseKey}
  lowDataMode: true
kubeEvents:
  enabled: true
webhook:
  enabled: true
prometheus:
  enabled: true
logging:
  enabled: true
ksm:
  enabled: false
newrelic-infrastructure:
  privileged: true
newrelic-pixie:
  apiKey: ${pixieApiKey}
  enabled: true
pixie-chart:
  clusterName: ${clusterName}
  deployKey: ${pixieChartKey}
  enabled: true
```

We're deploying to an EKS cluster and from what I've observed, the `pl-cluster-secrets` is created without the `cluster-id` key and gets updated latter with it, it takes about 3 to 5 minutes for the secret to get updated with the missing key, if after that we manually delete the failed Pod, the helm release resumes and finishes successfully but most of the time, the release fails if there's no manual intervention.
