### ISSUE TITLE
[newrelic-infrastructure-v3] if control plane disable not possible to scrape integrations

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/helm-charts#716]
**Bug description**

I believe that since we create:
```yaml
  - apiGroups: [ "" ]
    resources:
      - "pods"
      - "nodes"
    verbs: [ "get", "list", "watch" ]
```
if .Values.controlPlane.enabled the nri-discovery is not able to get such info if control plane is disabled.

We are connecting to the kubelet therefore it is a bit different, but still I believe that the request would be denied

**Which chart?**
newrelic infrastructure v3

Reproduction

Pending
