### ISSUE TITLE
[newrelic-infra-operator] 1.22 incopatibility

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/helm-charts#721]
Note that this is a bug not affecting us yet since EKS is not supporting 1.22 yet, but we need to fix it before the release "March, 2022"

<br class="Apple-interchange-newline">"

**Bug description**

Related to https://github.com/jet/kube-webhook-certgen/issues/30

**Version of Helm and Kubernetes**

k8s 1.22

**Which chart?**

newrelic-infra-operator

**What happened?**

The patch job looks for v1beta1 resources not finding them, update the image fixes the issue. We are already using the new image in different repos

```
  image:
    repository: k8s.gcr.io/ingress-nginx/kube-webhook-certgen
    tag: v1.1.1
    pullPolicy: IfNotPresent
```
