### ISSUE TITLE
[synthetics-minion] stderr F chown: changing ownership of '/tmp': Operation not permitted

### ISSUE THREAD

**Issue by pragmaticivan** [newrelic/helm-charts#742]
**Bug description**

Pod not able to start with the latest version of minion.

**Version of Helm and Kubernetes**

quay.io/newrelic/synthetics-minion:3.0.61
helm.sh/chart=synthetics-minion-1.0.49
K8s: `Major:"1", Minor:"21+"`

**Which chart?**

The chart name and version.

**What happened?**

Pod is not starting. Getting `stderr F chown: changing ownership of '/tmp': Operation not permitted`

**What you expected to happen?**

Pod should start.

**How to reproduce it?**

> values.yaml
```
replicaCount: 3

fullnameOverride: newrelic-symthetics-minion

synthetics:
  privateLocationKeySecretName: "newrelic-synthetics-credentials"

tolerations:
- key: CriticalAddonsOnly
  operator: Exists
```

**Anything else we need to know?**

Surprise us!
