### ISSUE TITLE
[nri-bundle] Global settings for imagePullSecrets aren't propagated to subcharts

### ISSUE THREAD

**Issue by hndrewaall** [newrelic/helm-charts#818]
**Bug description**

When defining imagePullSecrets, according to the docs for nri-bundle 4.3.3, I should be able to use settings like the following

```yaml
global:
  images:
    pullSecrets:
      - name: my-docker-creds
```

However, while this results in global settings that propagate to the global settings of subcharts, they aren't actually included in the rendered templates. See the output of `helm template` or `helm upgrade -i --debug --dry-run` for an example. 

**Version of Helm and Kubernetes**
```
$ helm version                                                                                                                                                                                    1 ↵
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-19T17:27:39Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-eks-f17b81", GitCommit:"f17b810c9e5a82200d28b6210b458497ddfcf31b", GitTreeState:"clean", BuildDate:"2021-10-15T21:46:21Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart?**

nri-bundle, v4.3.3

**What you expected to happen?**

I should see the same rendered templates as I do as when I explicitly define the pull secrets on the subcharts, as below:
```yaml
kubeEvents:
  enabled: true
  images:
    pullSecrets:
      - name: my-docker-creds

newrelic-infrastructure:
  privileged: true
  images:
    pullSecrets:
      - name: my-docker-creds
```

**Comment by kang-makes** [comment]
There were a bunch of issues that made that happen. Some of them were already solved but should be completely solved when we merge newrelic/k8s-metadata-injection#181 and newrelic/newrelic-infra-operator#179 and update the dependencies for `nri-bundle`.

We still have to solve this horrible UX that came from legacy but you were also configuring it incorrectly. The values should look like this:
```yaml
kubeEvents:
  enabled: true
  
nri-kube-events:
  images:
    pullSecrets:
      - name: my-docker-creds
      
newrelic-infrastructure:
  privileged: true
  images:
    pullSecrets:
      - name: my-docker-creds
```

After these fixes, using `global.images.pullSecrets` should do the trick.

Sorry for any inconvenience.
