### ISSUE TITLE
[pixie-chart] Annotations not applied on pixie resources

### ISSUE THREAD

**Issue by hassan-cevo** [newrelic/helm-charts#853]
**Bug description**

Annotations to the pixie chart are not getting applies to pixie resources.

**Version of Helm and Kubernetes**

Kubernetes version 1.21. Helm v3.6.3.

**Which chart?**

nri-bundle version: "4.4.6"

**What happened?**

I want to apply annotations for all resources created by pixie-chart. The pixie chart gives this option by using helm `--set` which is mentioned here

https://docs.pixielabs.ai/reference/admin/deploy-options/#annotating-pixie's-resources

I have updated the nri-bundle helm chart as below. Tried to use both `annotations` and `podAnnotations`.

```yaml
  values:
    pixie-chart:
      enabled: true
      annotations:
        linkerd.io/inject: disabled
      podAnnotations:
        linkerd.io/inject: disabled
      clusterName: dev1-data-platform-cluster
      pemMemoryLimit: 3Gi
    newrelic-pixie:
      enabled: true
      resources:
        limits:
          memory: 3Gi
```

The problem I am facing is that none of the pixie resources get annotated.

**What you expected to happen?**

Annotations mentioned in the pixie-chart should be applied to all resources created by pixie-chart. 

**How to reproduce it?**

Use the annotation given in the yaml values as above. 

**Anything else we need to know?**

The problem was raised with pixie open source and they refused to look into it as it is not the open source offering but an enterprise one through New Relic which should be looked by enterprise using pixie.
